# Book settings
title: Elements of Data Science
author: Allen B. Downey

latex:
  latex_documents:
    targetname: book.tex

execute:
  execute_notebooks: 'off'

repository:
  url: https://github.com/AllenDowney/ElementsOfDataScience/tree/v1
html:
  use_repository_button: true

  extra_footer: |
    <div style="text-align: left;">
      <a rel="license" href="https://creativecommons.org/licenses/by-nc-sa/4.0/">
        <img alt="Creative Commons License" style="border-width:0"
             src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" />
      </a>
      <br />
      This work is licensed under a
      <a rel="license" href="https://creativecommons.org/licenses/by-nc-sa/4.0/">
        Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License
      </a>.
    </div>
