#!/bin/bash
# Commit and push the notebooks generated by build.sh.
#
# Usage: ./publish.sh "commit message"
#
# Readers open these notebooks on Colab straight from GitHub, so pushing
# publishes them. Run build.sh and `make tests` first.

set -e
cd "$(dirname "$0")"

if [ -z "$1" ]; then
    echo "Usage: $0 \"commit message\"" >&2
    exit 1
fi

git add [01]*.ipynb jupyter_intro.ipynb geo_example.ipynb clustering.ipynb \
    utils.py EDS_notebooks.zip
git commit -m "$1"
git push
